logsBucket: 'gs://notional-cocoa-470007-p5-build-logs'
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/api-gateway:$SHORT_SHA', '.']
  dir: 'api-gateway'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/identity-service:$SHORT_SHA', '.']
  dir: 'identity-service'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/media-service:$SHORT_SHA', '.']
  dir: 'media-service'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/post-service:$SHORT_SHA', '.']
  dir: 'post-service'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/search-service:$SHORT_SHA', '.']
  dir: 'search-service'

- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    sed -i "s/PROJECT_ID_PLACEHOLDER/$PROJECT_ID/g" k8s/*.yaml
    sed -i "s/TAG_PLACEHOLDER/$SHORT_SHA/g" k8s/*.yaml

- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud container clusters get-credentials social-media-cluster --region asia-south1
    kubectl apply -f k8s/

images:
- 'gcr.io/$PROJECT_ID/api-gateway:$SHORT_SHA'
- 'gcr.io/$PROJECT_ID/identity-service:$SHORT_SHA'
- 'gcr.io/$PROJECT_ID/media-service:$SHORT_SHA'
- 'gcr.io/$PROJECT_ID/post-service:$SHORT_SHA'
- 'gcr.io/$PROJECT_ID/search-service:$SHORT_SHA'