logsBucket: 'gs://notional-cocoa-470007-p5-build-logs'
steps:
# Build all 5 service images
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/api-gateway:$SHORT_SHA', '.']
  dir: 'api-gateway'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/identity-service:$SHORT_SHA', '.']
  dir: 'identity-service'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/media-service:$SHORT_SHA', '.']
  dir: 'media-service'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/post-service:$SHORT_SHA', '.']
  dir: 'post-service'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/search-service:$SHORT_SHA', '.']
  dir: 'search-service'

# NEW STEP: Find and replace the placeholders in our k8s files
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    sed -i "s/PROJECT_ID_PLACEHOLDER/$PROJECT_ID/g" k8s/*.yaml
    sed -i "s/TAG_PLACEHOLDER/$SHORT_SHA/g" k8s/*.yaml

# Connect to our GKE cluster
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['container', 'clusters', 'get-credentials', 'social-media-cluster', '--region', 'asia-south1']

# Deploy our updated manifests to GKE!
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'k8s/']

images:
- 'gcr.io/$PROJECT_ID/api-gateway:$SHORT_SHA'
- 'gcr.io/$PROJECT_ID/identity-service:$SHORT_SHA'
- 'gcr.io/$PROJECT_ID/media-service:$SHORT_SHA'
- 'gcr.io/$PROJECT_ID/post-service:$SHORT_SHA'
- 'gcr.io/$PROJECT_ID/search-service:$SHORT_SHA'