apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  annotations:
    # This is the new line that links our custom health check
    cloud.google.com/backend-config: '{"ports": {"80":"my-backend-config"}}'
spec:
  # This should be NodePort, not LoadBalancer, for GKE Ingress
  type: NodePort
  selector:
    app: api-gateway
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000