# k8s/api-gateway-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: 'gcr.io/PROJECT_ID_PLACEHOLDER/api-gateway:TAG_PLACEHOLDER'
        ports:
        - containerPort: 3000