apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity-service
  template:
    metadata:
      labels:
        app: identity-service
    spec:
      containers:
      - name: identity-service
        image: 'gcr.io/$_PROJECT_ID/identity-service:v1'
        ports:
        - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: identity-service
spec:
  selector:
    app: identity-service
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 3001