apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: media-service
  template:
    metadata:
      labels:
        app: media-service
    spec:
      containers:
      - name: media-service
        image: 'gcr.io/PROJECT_ID_PLACEHOLDER/media-service:TAG_PLACEHOLDER'

        envFrom:
        - configMapRef:
            name: media-service-config
        - secretRef:
            name: media-service-secret

        ports:
        - containerPort: 3003
---
apiVersion: v1
kind: Service
metadata:
  name: media-service
spec:
  selector:
    app: media-service
  ports:
  - protocol: TCP
    port: 3003
    targetPort: 3003