apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search-service
  template:
    metadata:
      labels:
        app: search-service
    spec:
      containers:
      - name: search-service
        image: 'gcr.io/$PROJECT_ID/search-service:$SHORT_SHA'
        ports:
        - containerPort: 3004
---
apiVersion: v1
kind: Service
metadata:
  name: search-service
spec:
  selector:
    app: search-service
  ports:
  - protocol: TCP
    port: 3004
    targetPort: 3004